#!/bin/bash

### Define script variables
### ============================================================================

NAME="legionella"                                           # Name of the application
VIRTUALENV="/opt/legionella/legionella-backend"             # Path to virtualenv
DJANGODIR="/opt/legionella/legionella-backend/legionella"   # Django Project Directory
USER=django                                                 # the user to run as
GROUP=django                                                # the group to run as
NUM_WORKERS=5                                               # No. of worker processes Gunicorn should spawn
DJANGO_SETTINGS_MODULE=legionella.config.settingsdev        # Settings file that Gunicorn should use
DJANGO_WSGI_MODULE=legionella.wsgidev                       # WSGI module name
BIND=unix:/opt/legionella/legionella-backend/gunicorn/gunicorn.sock  # Socket


### Activate virtualenv and create environment variables
### ============================================================================

echo "Starting $NAME as `whoami`"
# Activate the virtual environment
cd $VIRTUALENV
source bin/activate
cd $DJANGODIR
# Defining the Environment Variables
# export DJANGO_SECRET_KEY='CHANGEME!!!8%ylffu)6j0ogx9a6*$ck2uuw3-7zbm2_j)#0%v=h0ax6rdkw0'
# export DATABASE_URL='postgres:///django_cookiecutter_fedora'
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH


### Start Gunicorn
### ============================================================================

exec gunicorn ${DJANGO_WSGI_MODULE}:application \
        --name $NAME \
        --workers $NUM_WORKERS \
        --user=$USER --group=$GROUP \
        --log-level=debug \
	--bind=$BIND \
--bind=127.0.0.1:8001
